### PR TITLE
MyBit Go Bounty: update web3 plugin + Metamask refactor - #600

### PR DESCRIPTION
**Pull request by mwood77**
## Source
Issue: https://github.com/MyBitFoundation/MyBit-Go.app/issues/600
Bounty: [MyBitFoundation/MyBit-Go.app/issues/600]( https://gitcoin.co/funding/details/?url=https://github.com/MyBitFoundation/MyBit-Go.app/issues/600)

## Acceptance criteria
- [x] Lets users see the assets on the landing page without having the Metamask plugin installed in their browser.
- [ ] Move the Metamask prompt for install/login to the point of sale.
- [x]  Update Web3 page injection deprecation from the Jan/Feb Metamask update.
    - commit: ee4f9244436c3470e6b3284a1746400a5134ea96 
- [x] Have this functionality implemented with no bugs or breaking changes to the existing app workflow.

## Housekeeping
- Corrected various import statements (`ui/` -> `UI/*`)
    - commit:  cc784fa6ea426f6a605b83bad3b801eb2664e883
    - commit: b6788962d2158154d367254ae782c66552f49f40
- Corrected Vercel container warning
    - commit:  194a6e185894cf6885401d3a0476ad68433ab737
- Updated NodeJS from 10 to latest LTS (14.17.0)
   - commit: e2f74d9a3f30c1776a39623776c3e2fac3cb9ec8
- Fixed dockerfile (unsure if needed, but could've been related to Vercel/Travis issues)
   - commit: 11194d5285be62a8ab8402477587e75155419659

## Further Reading
- https://medium.com/metamask/breaking-changes-to-the-metamask-provider-are-here-7b11c9388be9
- https://docs.metamask.io/guide/provider-migration.html

### CODE REVIEW

**Comment by mwood77** [comment]
## ⚠️ blocker
[see comment regarding next steps - Vercel and AirTable](https://github.com/MyBitFoundation/MyBit-Go.app/issues/600#issuecomment-847028156)

**Comment by mwood77** [comment]
@rd123myb 
I think I've hit the final wall. I've raised a PR for the work done. This mostly focuses on fixing the compatibility issues with Metamask, removing the errors logged in the console, and updating the Web3 library.

What you'll notice:
- When you go to the site, it no longer renders a white page (it recognizes that there is no connected wallet, and bypasses the previous methods that were causing the 'white page error').
- Connecting a wallet allows the app to detect/search for assets to render (this is dependent on AirTable).
- I've updated the documentation to state explicitly that the project requires Node 10. I attempted to update this to Node 14 (latest LTS as of writing, but it created a number of other issues). 10 is no longer an LTS as of April 2021, but it should be fine for the time being.

Concerns:
- I believe there's still an issue with your deployment setup, as we've discussed offline. Unfortunately there's nothing I can do to fix it as an outside collaborator. You'll need somebody with MyBit's organization permissions to address this issue.

**Comment by ariesvtb817** [comment]
Where are we on this? Raising a flag in the MyBit community forums for internal support. @mwood77 fantastic work by the way. Hope to see this project developed further. High prospects here

**Comment by mwood77** [comment]
Hi @ariesvtb817 there will be an update in the Telegram group soon. There has been some further issues encountered behind the scenes regarding MyBit's infrastructure.

**Comment by mwood77** [comment]
Abandoning this PR, as what is required is outside of the scope of the original ticket. Ticket will not be completed.

**Pull request closed without merging**
