### PR TITLE
fix docker error

### PR DESCRIPTION
**Pull request by revealtheweb**
This PR fixes Docker error which causes build to always fail.

### CODE REVIEW

**Comment by cryptnotiq** [comment]
can you re-open this PR and recreate the branch you deleted? I can't merge the pull request bc of that. @revealtheweb

**Comment by revealtheweb** [comment]
@cryptnotiq The PR doesn't  fix the issue that's why I closed it. The problem lies in the fact that Now.sh no longer supports docker deployments which is used to deploy the app, so simply removing the "--docker" flag does not solve the issue. From my research, the project has to be migrated to a current Now.sh deployment method. I also noticed that builds started failing on 11 Dec 2019, right after the time the support for docker was stopped.

**Comment by cryptnotiq** [comment]
@revealtheweb excuse my ignorance but is that migration easy to do or will it take extensive time?

**Comment by revealtheweb** [comment]
@cryptnotiq for an existing system like this, migration will take a fairly valuable amount of time. As a possible but risky alternative, you could set up travis and circle CI to still deploy without passing all checks, but that would open up the system to potential bugs. So I highly discourage that. The best option is to migrate as directed by Now.sh

**Comment by cryptnotiq** [comment]
ok thanks for your research @revealtheweb

**Comment by cryptnotiq** [comment]
@revealtheweb can you please share your telegram ID so we can discuss manual deployment there?

**Comment by revealtheweb** [comment]
@cryptnotiq  Telegram is: @revealtheweb

**Pull request closed without merging**
